SSC - Octane integration - inject SSC vulnerabilities to Octane -us #587042 : Fortify OnPrem E2E
MicroFocus/hpaa-octane-dev pull request #124
Opened 2018-10-04 13:21 UTC by yamin-hijazi

SSC integration code.

2018-10-04 13:22 UTC, yamin-hijazi commented
Reviewed by Radi.

2018-10-05 07:30 UTC, m-seldin commented
@yamin-hijazi 
please check appveyor build failures
please check codacy errors
please enter proper pull request title and description (with jira and octane issues numbers)

2018-10-05 08:03 UTC, m-seldin requested changes
please correct changes in comments

2018-10-05 08:03 UTC, m-seldin commented on src/main/java/com/microfocus/application/automation/tools/octane/configuration/SSCServerConfigUtil.java
> +package com.microfocus.application.automation.tools.octane.configuration;
@yamin-hijazi 
add license

2018-10-05 08:03 UTC, m-seldin commented on src/main/java/com/microfocus/application/automation/tools/octane/configuration/SSCServerConfigUtil.java
> +public class SSCServerConfigUtil {
add class documentation

2018-10-06 22:43 UTC, m-seldin commented
appveyor still failing.
no jira issue

2018-10-11 07:40 UTC, merged